ALTER TABLE users ADD COLUMN status VARCHAR(20);

UPDATE users
SET status = CASE WHEN active THEN 'ACTIVE' ELSE 'INACTIVE' END;

ALTER TABLE users ALTER COLUMN status SET NOT NULL;
ALTER TABLE users ALTER COLUMN status SET DEFAULT 'PENDING';

CREATE INDEX idx_users_status ON users(status);
